using System.Security.Cryptography;
using System.Text;

namespace Task_DirectoryTracker.Services.Common;

/// <summary>
/// This static class provides extenstion methods for building files.
/// </summary>
internal static class FileBuilder
{
    /// <summary>
    /// Builds a file name based on the given path and file extension arguments. <br />
    /// The file name is generated by computing the SHA256 hash of the path and converting it to a hexadecimal string, then appending the specified file extension.
    /// </summary>
    /// <param name="path"> The input path for which to generate the file name. It is typically the root path of a directory snapshot.</param>
    /// <param name="fileExtension">The file extension to append to the generated file name.</param>
    /// <returns>The generated file name.</returns>
    internal static string BuildFileName(string path, string fileExtension)
    {
        byte[] bytes = SHA256.HashData(Encoding.UTF8.GetBytes(path));
        return Convert.ToHexString(bytes) + fileExtension;
    }
}
